try run jest test

diff --git a/.github/workflows/online-experiments.yml b/.github/workflows/online-experiments.yml
--- a/.github/workflows/online-experiments.yml
+++ b/.github/workflows/online-experiments.yml
@@ -12,12 +12,18 @@ on:
     branches: [main]
 #
 jobs:
-  build-1:
+  nightly_job:
     timeout-minutes: 60
     runs-on: ${{ matrix.os }}
     outputs:
-      output1: ${{ steps.vars.outputs.tag-name }}
-      output2: ${{ steps.vars.outputs.isRunAppium }}
+      tag-name: '0.2.1-nightly-202302151843'
+      release-name: ${{ steps.unify.outputs.release-name }}
+      package-name: ${{ steps.unify.outputs.package-name }}
+      isRunAppium: ${{ steps.check.outputs.isRunAppium }}
+      isModifyReleaseJson: ${{ steps.unify.outputs.isModifyReleaseJson }}
+      repository: ${{ github.repository }}
+      display-name: ${{ steps.slug.outputs.display-name }}
+      file-name-lower: ${{ steps.slug.outputs.file-name-lower }}
     strategy:
       matrix:
         # os: [ubuntu-latest, windows-latest, macos-latest]
@@ -224,7 +230,7 @@ jobs:
           echo "MODIFIED_FILE_LIST: ${{ env.MODIFIED_FILE_LIST }}"
           if ${{ contains(env.MODIFIED_FILE_LIST, 'release.json') }} ; \
           then echo "isRunAppium=1" >> $GITHUB_OUTPUT ; \
-          else echo "isRunAppium=0" >> $GITHUB_OUTPUT ; \
+          else echo "isRunAppium=1" >> $GITHUB_OUTPUT ; \
           fi
           echo "unify----------------------"
           echo "tag-name: ${{ steps.unify.outputs.tag-name }}"
@@ -234,58 +240,58 @@ jobs:
           echo "commit-sha7: ${{ steps.nightly.outputs.commit-sha7 }}"
         shell: bash
 
-      - name: Install dependencies 👨🏻‍💻
-        uses: nick-fields/retry@v2
-        with:
-          timeout_seconds: 600
-          max_attempts: 2
-          shell: bash
-          retry_on: error
-          command: yarn
-          on_retry_command: rm -rf C:/Users/runneradmin/AppData/Local/node-gyp/
+      # - name: Install dependencies 👨🏻‍💻
+      #   uses: nick-fields/retry@v2
+      #   with:
+      #     timeout_seconds: 600
+      #     max_attempts: 2
+      #     shell: bash
+      #     retry_on: error
+      #     command: yarn
+      #     on_retry_command: rm -rf C:/Users/runneradmin/AppData/Local/node-gyp/
 
-      - name: Install UnPackaged 👨🏻‍💻
-        uses: nick-fields/retry@v2
-        with:
-          timeout_seconds: 600
-          max_attempts: 2
-          shell: bash
-          retry_on: error
-          command: yarn unpackaged
-          on_retry_command: rm -rf C:/Users/runneradmin/AppData/Local/node-gyp/
+      # - name: Install UnPackaged 👨🏻‍💻
+      #   uses: nick-fields/retry@v2
+      #   with:
+      #     timeout_seconds: 600
+      #     max_attempts: 2
+      #     shell: bash
+      #     retry_on: error
+      #     command: yarn unpackaged
+      #     on_retry_command: rm -rf C:/Users/runneradmin/AppData/Local/node-gyp/
 
-      - name: check arch
-        run: |
-          uname -a
-          arch
+      # - name: check arch
+      #   run: |
+      #     uname -a
+      #     arch
 
-      - name: Run electron-packager
-        run: |
-          if ${{ contains(env.MODIFIED_FILE_LIST, 'release.json') }} ; \
-          then if ${{ contains(steps.release.outputs.new-tag-name, 'nightly') }} ; \
-            then yarn node update-version.js --newTag ${{ steps.unify.outputs.tag-name }} --SHA7 ${{ steps.sha.outputs.sha7 }} --buildTime ${{ steps.vars.outputs.date }} ; \
-            else yarn node update-version.js --newTag ${{ steps.unify.outputs.tag-name }} --SHA7 ${{ steps.sha.outputs.sha7 }} --buildTime ${{ steps.vars.outputs.date }} --stable; \
-            fi
-          else yarn node update-version.js --buildTime ${{ steps.vars.outputs.date }} ; \
-          fi
-          brew install coreutils
-          chmod +x ./universal/build-mac.sh && ./universal/build-mac.sh --dev
+      # - name: Run electron-packager
+      #   run: |
+      #     if ${{ contains(env.MODIFIED_FILE_LIST, 'release.json') }} ; \
+      #     then if ${{ contains(steps.release.outputs.new-tag-name, 'nightly') }} ; \
+      #       then yarn node update-version.js --newTag ${{ steps.unify.outputs.tag-name }} --SHA7 ${{ steps.sha.outputs.sha7 }} --buildTime ${{ steps.vars.outputs.date }} ; \
+      #       else yarn node update-version.js --newTag ${{ steps.unify.outputs.tag-name }} --SHA7 ${{ steps.sha.outputs.sha7 }} --buildTime ${{ steps.vars.outputs.date }} --stable; \
+      #       fi
+      #     else yarn node update-version.js --buildTime ${{ steps.vars.outputs.date }} ; \
+      #     fi
+      #     brew install coreutils
+      #     chmod +x ./universal/build-mac.sh && ./universal/build-mac.sh --dev
 
-      - name: check
-        run: |
-          cd build
-          ls
-          echo "---------------"
-          cd electron
-          ls
-        shell: bash
+      # - name: check
+      #   run: |
+      #     cd build
+      #     ls
+      #     echo "---------------"
+      #     cd electron
+      #     ls
+      #   shell: bash
 
-      - name: Upload packager Results 🗃
-        if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: "${{ matrix.os }}-output"
-          path: ./mac-build.log
+      # - name: Upload packager Results 🗃
+      #   if: always()
+      #   uses: actions/upload-artifact@v2
+      #   with:
+      #     name: "${{ matrix.os }}-output"
+      #     path: ./mac-build.log
 
       # # fix lxd dir error in ubuntu20.04
       # - name: fix lxd dir error
@@ -301,34 +307,33 @@ jobs:
       # - name: Build snap 📦
       #   run: yarn make:snap:ci
 
-      - name: Release ${{ steps.slug.outputs.file-name-lower }}-${{ steps.unify.outputs.package-name }}-${{ steps.vars.outputs.system }} to GitHub 📰
-        uses: softprops/action-gh-release@v1
-        with:
-          prerelease: true
-          name: ${{ steps.slug.outputs.file-name-lower }}-${{ steps.unify.outputs.release-name }}
-          tag_name: ${{ steps.unify.outputs.tag-name }}
-          body: ${{ env.DESCRIBE }}
-          files: |
-            ./out/installers/${{ steps.unify.outputs.tag-name }}/**
+      # - name: Release ${{ steps.slug.outputs.file-name-lower }}-${{ steps.unify.outputs.package-name }}-${{ steps.vars.outputs.system }} to GitHub 📰
+      #   uses: softprops/action-gh-release@v1
+      #   with:
+      #     prerelease: true
+      #     name: ${{ steps.slug.outputs.file-name-lower }}-${{ steps.unify.outputs.release-name }}
+      #     tag_name: ${{ steps.unify.outputs.tag-name }}
+      #     body: ${{ env.DESCRIBE }}
+      #     files: |
+      #       ./out/installers/${{ steps.unify.outputs.tag-name }}/**
 
-  appium-test:
-    needs: build-1
+  appium_test_job:
+    needs: [nightly_job, release_job]
     if: |
-      (contains(github.event_name, 'schedule') || contains(needs.build-1.outputs.output2, '2'))
+      (contains(github.event_name, 'schedule') || contains(needs.nightly_job.outputs.isRunAppium, '1'))
         && !contains(github.event.head_commit.message, 'skip e2e')
-    timeout-minutes: 60
+    timeout-minutes: 120
     runs-on: ${{ matrix.os }}
     strategy:
-      fail-fast: false
       matrix:
         test: [1, 2]
         node-version: [14]
-        os: [windows-2022]
+        os: [windows-latest]
         include:
           - test: 1
-            os: windows-2022
+            os: windows-latest
           - test: 2
-            os: windows-2022
+            os: windows-latest
     environment:
       name: CICD
     env:
@@ -346,12 +351,17 @@ jobs:
       TEST3_PHONE_NUMBER: ${{ secrets.TEST3_PHONE_NUMBER }}
       TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
       TEST_RESET_PASSWORD: ${{ secrets.TEST_RESET_PASSWORD }}
+      TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
+      TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
+      TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
+      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
     steps:
-      - name: test Get short SHA 🔑
+      - name: appium_test_job Get short SHA 🔑
         run: |
-          echo "::set-output name=sha7::${GITHUB_SHA::7}"
-          echo "test-1"
-          echo "isRunAppium: ${{needs.build-1.outputs.output2}}"
+          echo "sha7=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
+          echo "nightly_job"
+          echo "isRunAppium: ${{needs.nightly_job.outputs.isRunAppium}}"
+          echo "repository: ${{needs.nightly_job.outputs.repository}}"
         shell: bash
 
       - name: Checkout ⬇️
@@ -368,7 +378,6 @@ jobs:
           NODE_AUTH_TOKEN: ${{ secrets.PAT }}
 
       - name: update node-gyp on windows to support Visual Studio 2019
-        if: matrix.os == 'windows-2022'
         shell: powershell
         run: |
           npm install --global node-gyp@8.4.1
@@ -388,10 +397,10 @@ jobs:
           retry_on: error
           command: yarn
 
-      - name: Install Alphabiz
+      - name: Install ${{ needs.nightly_job.outputs.file-name-lower }}.7z
         run: |
-          curl -L https://github.com/tanshuai/alphabiz/releases/download/${{needs.build-1.outputs.output1}}/alphabiz-${{needs.build-1.outputs.output1}}-windows.7z > alphabiz.7z
-          7z x alphabiz.7z
+          curl -L https://github.com/${{ needs.nightly_job.outputs.repository }}/releases/download/${{needs.nightly_job.outputs.tag-name}}/${{ needs.nightly_job.outputs.file-name-lower }}-${{needs.nightly_job.outputs.tag-name}}-windows.7z > appPackage.7z
+          7z x appPackage.7z
         shell: bash
 
       - name: Install winappdriver.msi
@@ -407,72 +416,72 @@ jobs:
           Start-Process PowerShell -ArgumentList "yarn test:appium"
           Start-Sleep -s 10
 
-      - name: e2e appium creditDownload test for 7z 🧪
+      - name: E2E appium creditDownload test for 7z 🧪
         if: matrix.test == '1'
         uses: nick-fields/retry@v2
         with:
-          timeout_seconds: 1200
+          timeout_seconds: 1800
           max_attempts: 2
           shell: bash
           retry_on: error
           command: |
-            taskkill //F //IM Alphabiz.exe || (echo "app is ready")
+            taskkill //F //IM ${{ needs.nightly_job.outputs.display-name }}.exe || (echo "app is ready")
             sleep 10s
             yarn test:release:creditsDownload
 
-      - name: e2e appium creditUpload test for 7z 🧪
+      - name: E2E appium creditUpload test for 7z 🧪
         if: matrix.test == '2'
         uses: nick-fields/retry@v2
         with:
-          timeout_seconds: 1200
+          timeout_seconds: 1800
           max_attempts: 2
           shell: bash
           retry_on: error
           command: |
-            taskkill //F //IM Alphabiz.exe || (echo "app is ready")
+            taskkill //F //IM ${{ needs.nightly_job.outputs.display-name }}.exe || (echo "app is ready")
             sleep 10s
             yarn test:release:creditsUpload
 
       - name: Download msi and exe
         run: |
-          curl -L https://github.com/tanshuai/alphabiz/releases/download/${{needs.build-1.outputs.output1}}/alphabiz-${{needs.build-1.outputs.output1}}.exe > C:/alphabiz.exe
-          curl -L https://github.com/tanshuai/alphabiz/releases/download/${{needs.build-1.outputs.output1}}/alphabiz-${{needs.build-1.outputs.output1}}.msi > C:/alphabiz.msi
+          curl -L https://github.com/${{ needs.nightly_job.outputs.repository }}/releases/download/${{needs.nightly_job.outputs.tag-name}}/${{ needs.nightly_job.outputs.file-name-lower }}-${{needs.nightly_job.outputs.tag-name}}.exe > C:/appPackage.exe
+          curl -L https://github.com/${{ needs.nightly_job.outputs.repository }}/releases/download/${{needs.nightly_job.outputs.tag-name}}/${{ needs.nightly_job.outputs.file-name-lower }}-${{needs.nightly_job.outputs.tag-name}}.msi > C:/appPackage.msi
         shell: bash
 
-      - name: Install alphabiz.msi
+      - name: Install ${{ needs.nightly_job.outputs.file-name-lower }}.msi
         run: |
-          Start-Process msiexec -ArgumentList "/quiet","/i","C:\alphabiz.msi"
+          Start-Process msiexec -ArgumentList "/quiet","/i","C:\appPackage.msi"
         shell: powershell
 
-      - name: Install alphabiz.exe
+      - name: Install ${{ needs.nightly_job.outputs.file-name-lower }}.exe
         run: |
-          Start-Process -FilePath "C:\alphabiz.exe" -Verb runAs -ArgumentList '/s','/v"/qn"'
+          Start-Process -FilePath "C:\appPackage.exe" -Verb runAs -ArgumentList '/s','/v"/qn"'
           Start-Sleep -s 30
         shell: powershell
 
-      - name: e2e appium test for msi 🧪
+      - name: E2E appium test for msi 🧪
         uses: nick-fields/retry@v2
         with:
-          timeout_seconds: 1200
+          timeout_seconds: 1800
           max_attempts: 2
           shell: bash
           retry_on: error
           command: |
-            taskkill //F //IM Alphabiz.exe || (echo "app is ready")
+            taskkill //F //IM ${{ needs.nightly_job.outputs.display-name }}.exe || (echo "app is ready")
             sleep 10s
             export APP_TYPE=msi
             yarn test:release
             unset APP_TYPE
 
-      - name: e2e appium test for exe 🧪
+      - name: E2E appium test for exe 🧪
         uses: nick-fields/retry@v2
         with:
-          timeout_seconds: 1200
+          timeout_seconds: 1800
           max_attempts: 2
           shell: bash
           retry_on: error
           command: |
-            taskkill //F //IM Alphabiz.exe || (echo "app is ready")
+            taskkill //F //IM ${{ needs.nightly_job.outputs.display-name }}.exe || (echo "app is ready")
             sleep 10s
             export APP_TYPE=exe
             yarn test:release
